spring.application.name=cursoSpringBoot
server.port=8080
server.servlet.context-path=/sistema/api/v1
service.products=json

# CONFIGURACIÓN PERSONALIZADA DE APP
app.name=Sistema de productos
app.version=1.0.0
app.author=Jef
app.language=es
app.country=EC
